load("//Config:buck_rule_macros.bzl", "static_library")

static_library(
    name = "Facegram",
    srcs = glob([
        "Facegram/**/*.swift",
    ]),
    deps = [
        "//submodules/SSignalKit/SwiftSignalKit:SwiftSignalKit#shared",
        "//submodules/AsyncDisplayKit:AsyncDisplayKit#shared",
        "//submodules/Display:Display#shared",
        "//submodules/Postbox:Postbox#shared",
        "//submodules/TelegramCore:TelegramCore#shared",
        "//submodules/SyncCore:SyncCore#shared",
        "//submodules/TelegramPresentationData:TelegramPresentationData",
        "//submodules/AccountContext:AccountContext",
        "//submodules/AnimationUI:AnimationUI",
        "//submodules/AppBundle:AppBundle",
        "//submodules/ItemListUI:ItemListUI",
        "//submodules/SearchUI:SearchUI",
        "//submodules/TelegramNotices:TelegramNotices",
        "//submodules/PhoneNumberFormat:PhoneNumberFormat",
        "//submodules/DeviceAccess:DeviceAccess",
        "//submodules/TelegramUIPreferences:TelegramUIPreferences",
        "//submodules/TelegramPermissionsUI:TelegramPermissionsUI",
        "//submodules/ContextUI:ContextUI",
        "//submodules/AvatarNode:AvatarNode",
        "//submodules/PresentationDataUtils:PresentationDataUtils",
        "//submodules/AuthTransferUI:AuthTransferUI",
        "//submodules/ItemListAvatarAndNameInfoItem:ItemListAvatarAndNameInfoItem",
        "//submodules/LanguageLinkPreviewUI:LanguageLinkPreviewUI",
    ],
    frameworks = [
        "$SDKROOT/System/Library/Frameworks/Foundation.framework",
        "$SDKROOT/System/Library/Frameworks/UIKit.framework",
    ],
)
